#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/CellLogMonitor.jar:$APPDIR/lib/core.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/RXTXcomm.jar:$APPDIR/lib/net.jar:$APPDIR/lib/eeml.jar" CellLogMonitor
